# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jbeto/Documents/SI/SI-Investigations

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jbeto/Documents/SI/SI-Investigations

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbeto/Documents/SI/SI-Investigations/CMakeFiles /home/jbeto/Documents/SI/SI-Investigations/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbeto/Documents/SI/SI-Investigations/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arrest

# Build rule for target.
arrest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrest
.PHONY : arrest

# fast build rule for target.
arrest/fast:
	$(MAKE) -f .Secret/Arrest/CMakeFiles/arrest.dir/build.make .Secret/Arrest/CMakeFiles/arrest.dir/build
.PHONY : arrest/fast

#=============================================================================
# Target rules for targets named database

# Build rule for target.
database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 database
.PHONY : database

# fast build rule for target.
database/fast:
	$(MAKE) -f .Secret/Database/CMakeFiles/database.dir/build.make .Secret/Database/CMakeFiles/database.dir/build
.PHONY : database/fast

#=============================================================================
# Target rules for targets named talkto

# Build rule for target.
talkto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 talkto
.PHONY : talkto

# fast build rule for target.
talkto/fast:
	$(MAKE) -f .Secret/Talkto/CMakeFiles/talkto.dir/build.make .Secret/Talkto/CMakeFiles/talkto.dir/build
.PHONY : talkto/fast

#=============================================================================
# Target rules for targets named notes

# Build rule for target.
notes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 notes
.PHONY : notes

# fast build rule for target.
notes/fast:
	$(MAKE) -f .Secret/Notes/CMakeFiles/notes.dir/build.make .Secret/Notes/CMakeFiles/notes.dir/build
.PHONY : notes/fast

#=============================================================================
# Target rules for targets named investigate

# Build rule for target.
investigate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 investigate
.PHONY : investigate

# fast build rule for target.
investigate/fast:
	$(MAKE) -f .Secret/Investigate/CMakeFiles/investigate.dir/build.make .Secret/Investigate/CMakeFiles/investigate.dir/build
.PHONY : investigate/fast

#=============================================================================
# Target rules for targets named commands

# Build rule for target.
commands: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commands
.PHONY : commands

# fast build rule for target.
commands/fast:
	$(MAKE) -f .Secret/Commands/CMakeFiles/commands.dir/build.make .Secret/Commands/CMakeFiles/commands.dir/build
.PHONY : commands/fast

#=============================================================================
# Target rules for targets named login

# Build rule for target.
login: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 login
.PHONY : login

# fast build rule for target.
login/fast:
	$(MAKE) -f .Secret/Login/CMakeFiles/login.dir/build.make .Secret/Login/CMakeFiles/login.dir/build
.PHONY : login/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... arrest"
	@echo "... database"
	@echo "... talkto"
	@echo "... notes"
	@echo "... investigate"
	@echo "... commands"
	@echo "... login"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

